const D=JSON.parse(document.getElementById('dataset').textContent),$=id=>document.getElementById(id),layers=new Map(D.layers.map(l=>[l.id,l]));
const colors={'生活設施':'#16877b','交通出行':'#4178b4','環保回收':'#729237','公園自然':'#287440','動物友善':'#a17846','文化探索':'#a65e53','商業旅遊':'#7c67a2','免費上網':'#3b99b3','公共服務':'#777e86'};
let category='',source='',query='',visible=[],limit=60,origin=null,page=0,selected=null;
function el(tag,txt,cls){const e=document.createElement(tag);if(txt!=null)e.textContent=txt;if(cls)e.className=cls;return e}function date(x){return x?x.slice(0,10):'未提供'}function link(text,url){const a=el('a',text);if(/^https:\/\//.test(url)){a.href=url;a.target='_blank';a.rel='noopener noreferrer'}return a}function badge(t){return el('span',t,'badge')}
const map=L.map('map',{zoomControl:true}).setView([22.164,113.559],12);let tiles;
if(location.protocol!=='file:'){tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);tiles.on('tileerror',()=>{$('mapnote').textContent='底圖暫未載入；地點搜尋仍可使用。'})}else $('mapnote').textContent='離線預覽：地點可搜尋；正式發佈後載入 OpenStreetMap 底圖。';
const group=L.markerClusterGroup({showCoverageOnHover:false,chunkedLoading:true,maxClusterRadius:48,iconCreateFunction:c=>L.divIcon({html:String(c.getChildCount()),className:'cluster',iconSize:[42,42]})}).addTo(map);
function setCategory(c){category=c;source='';$('layer').value='';render();for(const b of $('chips').children)b.classList.toggle('active',b.dataset.cat===c)}
for(const c of ['',...Object.keys(colors)]){const b=el('button',c||'全部');b.dataset.cat=c;b.classList.toggle('active',!c);b.onclick=()=>setCategory(c);$('chips').append(b)}
for(const l of D.layers){const o=el('option',(l.status==='ready'?'':'待整理 · ')+l.name+(l.count?' · '+l.count:''));o.value=l.id;o.disabled=l.status!=='ready';$('layer').append(o)}
function distance(p){if(!origin)return 0;const rad=Math.PI/180,a=(p.lat-origin.lat)*rad,b=(p.lng-origin.lng)*rad;return 6371000*2*Math.asin(Math.sqrt(Math.sin(a/2)**2+Math.cos(origin.lat*rad)*Math.cos(p.lat*rad)*Math.sin(b/2)**2))}
function render(){visible=D.points.filter(p=>(!category||p.layers.some(id=>layers.get(id)?.category===category))&&(!source||p.layers.includes(source))&&(!query||(p.name+' '+p.address+' '+p.category+' '+p.layers.map(id=>layers.get(id)?.name).join(' ')).toLowerCase().includes(query)));if(origin)visible.sort((a,b)=>distance(a)-distance(b));group.clearLayers();for(const p of visible){const m=L.marker([p.lat,p.lng],{icon:L.divIcon({html:'<span class="dot" style="background:'+colors[p.category]+'"></span>',className:'',iconSize:[15,15]}),title:p.name});m.on('click',()=>detail(p));group.addLayer(m)}$('count').textContent=visible.length.toLocaleString()+' 個地點';$('sortlabel').textContent=origin?'按直線距離排序':'按資料目錄排序';limit=60;renderList()}
function renderList(){$('results').replaceChildren();for(const p of visible.slice(0,limit)){const b=el('button',null,'result');b.append(badge(p.category),badge([...new Set(p.layers.map(id=>layers.get(id)?.methods))].join(' / ')),el('strong',p.name),el('small',p.address||'查看位置與政府資料'));if(origin)b.append(el('small','距離約 '+(distance(p)/1000).toFixed(2)+' 公里（直線）'));b.onclick=()=>{map.setView([p.lat,p.lng],17);detail(p)};$('results').append(b)}if(!visible.length)$('results').append(el('p','找不到符合條件的地點，試試其他名稱或圖層。','empty'));if(visible.length>limit){const b=el('button','載入更多地點','result');b.onclick=()=>{limit+=60;renderList()};$('results').append(b)}}
function detail(p){selected=p;$('detail').hidden=false;$('detailContent').replaceChildren();const root=$('detailContent');root.append(badge(p.category),el('h2',p.name));if(p.closed)root.append(el('p','資料標示：暫停開放','warning'));if(p.notice)root.append(el('p',p.notice,'warning'));const dl=el('dl');for(const [k,v] of [['地址',p.address],['開放時間',p.hours],['電話',p.tel],['設施',[p.accessible?'無障礙設施':'',p.family?'親子設施':''].filter(Boolean).join('、')],['說明',p.description],['輕型車收費',p.price]])if(v){dl.append(el('dt',k),el('dd',v))}root.append(dl);const a=link('用 Google Maps 開啟導航','https://www.google.com/maps/dir/?api=1&destination='+p.lat+','+p.lng);a.className='primary';root.append(a);for(const id of p.layers){const l=layers.get(id),s=el('div',null,'source');s.append(badge(l.methods),link(l.name,l.url),el('div',l.dept),el('div','資料取得：'+date(l.retrievedAt)+' · 更新頻率：'+l.frequency));root.append(s)}root.append(el('p','來源：'+D.sourceLabel+'。設施狀況以主管部門公布為準。','source'))}
$('close').onclick=()=>{$('detail').hidden=true};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('detail').hidden=true});$('search').oninput=e=>{query=e.target.value.trim().toLowerCase();render()};$('layer').onchange=e=>{source=e.target.value;category='';for(const b of $('chips').children)b.classList.toggle('active',!b.dataset.cat);render()};$('reset').onclick=()=>map.fitBounds([[22.108,113.523],[22.221,113.599]]);$('locate').onclick=()=>{if(!navigator.geolocation){$('mapnote').textContent='此瀏覽器不支援定位。';return}navigator.geolocation.getCurrentPosition(p=>{origin={lat:p.coords.latitude,lng:p.coords.longitude};L.circleMarker([origin.lat,origin.lng],{radius:7,color:'#246bcc',fillOpacity:1}).addTo(map);map.setView([origin.lat,origin.lng],15);render();$('mapnote').textContent='位置只在你的瀏覽器使用；距離為直線距離。'},()=>{$('mapnote').textContent='未能取得位置。請允許定位，或用名稱搜尋。'},{timeout:10000})};
function view(v){$('workspace').hidden=v!=='map';$('catalog').hidden=v==='map';$('mapTab').classList.toggle('active',v==='map');$('catalogTab').classList.toggle('active',v!=='map');if(v==='map')setTimeout(()=>map.invalidateSize(),0)}$('mapTab').onclick=()=>view('map');$('catalogTab').onclick=()=>{view('catalog');renderCatalog()};
for(const d of [...new Set(D.catalog.map(c=>c.dept))].sort()){const o=el('option',d);o.value=d;$('dept').append(o)}
function renderCatalog(){const q=$('catSearch').value.trim().toLowerCase(),dep=$('dept').value,method=$('method').value;const rows=D.catalog.filter(c=>(!q||(c.name+' '+c.description+' '+c.dept).toLowerCase().includes(q))&&(!dep||c.dept===dep)&&(!method||c.methods.includes(method)));page=Math.min(page,Math.max(0,Math.ceil(rows.length/40)-1));$('catCount').textContent=rows.length+' 個數據集 · 提供方式可重疊';$('tbody').replaceChildren();for(const c of rows.slice(page*40,(page+1)*40)){const tr=el('tr'),name=el('td'),l=layers.get(c.id);name.append(link(c.name,c.url),el('small',c.frequency+' · '+(c.formats||'')));const methodCell=el('td');methodCell.append(badge(c.methods));const status=el('td');if(l?.status==='ready'){const b=el('button','在地圖查看');b.onclick=()=>{source=c.id;category='';query='';for(const b of $('chips').children)b.classList.toggle('active',!b.dataset.cat);$('search').value='';$('layer').value=source;view('map');render()};status.append(b)}else status.textContent=l?'待整理':'未接入';tr.append(name,methodCell,el('td',c.dept),status);$('tbody').append(tr)}$('pageLabel').textContent=(rows.length?page+1:0)+' / '+Math.ceil(rows.length/40);$('prev').disabled=page===0;$('next').disabled=(page+1)*40>=rows.length}
for(const id of ['catSearch','dept','method'])$(id).addEventListener(id==='catSearch'?'input':'change',()=>{page=0;renderCatalog()});$('prev').onclick=()=>{page--;renderCatalog()};$('next').onclick=()=>{page++;renderCatalog()};$('coverage').textContent=D.layers.filter(l=>l.status==='ready').length+' 個已接入圖層 · '+D.catalog.length.toLocaleString()+' 個數據集';$('date').textContent='資料快照 · 整理於 '+date(D.generatedAt);render();
